from typing import Protocol


class ProviderProtocol(Protocol):
    def complete(self, messages: list[dict], max_tokens: int, temperature: float) -> str: ...
    async def complete_async(self, messages: list[dict], max_tokens: int, temperature: float) -> str: ...
    def max_context_tokens(self) -> int: ...
